services:
  postgres:
    image: postgres:17.5
    container_name: spring-boot-aop-jamon-postgres
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: account
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
